### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by EvanG13** [sfsu-csc-667-fall-2023/term-project-EvanG13#1]
# Overview
This milestone requires us to specify our term project goal and to create wireframes - a low-fidelity prototype of a web application that will be used for planning

## Submission
• Up to 5 mins to present your project specifications and wireframes 
• Only one person needs to present
• Please come prepared with an organized slide deck!

## Project Specifications
- [ ] Identify the features we will be implementing
- [ ] List the technologies that we will be using for the project
- [ ] Upload to Repo

## Wireframes 
- [ ] Paper a pencil only
- [ ] Draw each screen created. with user interactions documented for that screen. MUST document all major screens
- [ ] Upload to Repo
